### ISSUE TITLE
About the output file

### ISSUE THREAD

**Issue by wyj-lzu** [RemiAllio/MitoFinder#22] opened 2021-04-23 02:15 UTC
Hi! When I used mitofinder, I meet something wrong. In my output folder, I didn't find files such as [Seq_ID]_final_genes_NT.fasta . I only found [checkpoints.txt  done  intermediate_contigs  options.json  wyj_test_megahit.contigs.fa  wyj_test_megahit.log] in [Seq_id]_megahit folder. Is that right? How can I fix it ? Thanks

**Comment by RemiAllio** [comment] 2021-04-23 09:13
Hi!
Thank you for your comment.

The output files should be in the [Seq_ID]\_MitoFinder\_*\_Final_Results folder. If not, something went wrong during the analyses.
In this case, please attach the following files to your response: [Seq_ID]_MitoFinder.log; geneChecker_error.log; geneChecker.log.

Cheers,
Rémi

**Comment by wyj-lzu** [comment] 2021-04-24 04:45
OK， I will check it soon. Thanks!

**Comment by wyj-lzu** [comment] 2021-04-24 08:31
Hi! When I check my output file, I only find [seq id]_megahit.log and [seq id]_MitoFinder.log. I didn't find geneChecker_error.log; geneChecker.log. I put my two log files here.
[log.zip](https://github.com/RemiAllio/MitoFinder/files/6369241/log.zip)

**Comment by RemiAllio** [comment] 2021-04-24 08:54
Hi!

Thanks for the file.
Indeed, something went wrong during the analysis.

Without the other two log files it's difficult for me to identify what happened.
It seems that the assembly step run well. The job was interrupted during the analysis of the first mitochondrial-like contig. 

Could you please send me the result of ```ls *``` in the [Seq_ID] directory created by MitoFinder.
Also, what is the version of MitoFinder used? On which system (Linux/Mac)? 
Could you please run the [test cases]( https://github.com/RemiAllio/MitoFinder#test-cases) and tell me if you have the same issue (running the second test case should be sufficient and much faster)?  

Thank you and sorry for the inconvenience...
Cheers,
Rémi

**Comment by wyj-lzu** [comment] 2021-04-24 09:06
OK! Now I put the results here(tree format). And I will run the test case now.
I run MitoFinder on Linux and the version is 1.4.
[tree.txt](https://github.com/RemiAllio/MitoFinder/files/6369289/tree.txt)

**Comment by RemiAllio** [comment] 2021-04-24 10:04
Thanks for the tree !

That's pretty strange. It seems that the job was killed in the middle of the analysis for no apparent reason. 
Did you have an error in your terminal when running MitoFinder?

I look forward to knowing if the test case worked. 

Additionally, you can try to restart your job by doing exactly the same command. MitoFinder should restart after the assembly step:
```/data/01/user186/software/MitoFinder/mitofinder -j wyj_test -1 AS1-21_NDSW39199_1.clean.fq.gz -2 AS1-21_NDSW39199_2.clean.fq.gz -r mouse_mit_re.gb -o 5 -p 15```
I wonder if mouse_mit_re.gb contains mouse mitochondrial genome(s). If so, is it normal to use the genetic code 5 (insect mitochondrial code)? Anyhow, it is not the reason of the error you reported. Just wondering :-)

Hope we find the cause of your issue.
Cheers,
Rémi

**Comment by wyj-lzu** [comment] 2021-04-24 10:30
OK! I get it. Our server has a slurm program, I didn't get any error when running MitoFinder. But it told me COMPLETED. My friend told me that I should run again with --metaspades. And I try it now. About the -o option, I will learn more about it.When it finish, I will check it again.

Thanks for your help. Have a good weekend!

**Comment by RemiAllio** [comment] 2021-04-26 17:06
Hi!

Did you find a solution with your server? :-)

Cheers,
Rémi

**Comment by wyj-lzu** [comment] 2021-04-27 02:03
Hi!

Sorry for replying you late. On my server with my own data, it got the same error. And with test data, I got nothing in output folder.  :(    I wonder if any dependencies  were not installed?

**Comment by RemiAllio** [comment] 2021-04-27 09:50
Hi,

Ok, honestly I don't know what is going on. 

One solution would be to use a singularity container to run MitoFinder. I can create this container (with all dependencies installed inside) for you. 
Could you install [singularity](https://sylabs.io/guides/3.0/user-guide/installation.html#installation) (version >= 3.3) in your server?

Cheers,
Rémi

**Comment by wyj-lzu** [comment] 2021-04-27 13:00
Hi! 

Because I didn't have a root account, I have to ask the administrator to install the singularity.  :) Thanks for helping me so much !

**Comment by RemiAllio** [comment] 2021-04-27 13:10
Hi,

I understand that you need to ask the administrator to install it. This is often the case with shared servers. 
I am working on the singularity container. Please tell me when your administrator has installed singularity and if I am ready, I will share the container with you. 

If it works for you, I will then make the container available to everyone :-)
Cheers,
Rémi

**Comment by wyj-lzu** [comment] 2021-04-27 15:10
OK! Thanks a lot !

**Comment by RemiAllio** [comment] 2021-04-27 21:34
Hi,

Here is the link to download the container:
https://filesender.renater.fr/?s=download&token=c5fde788-c898-424c-8521-cde60813a458

Once the container downloaded and Singularity (version >= 3.0) installed, you should be able to use MitoFinder as follows:
```PATH/TO/MitoFinder_v1.4 -j [seqid] -1 [left_reads.fastq.gz] -2 [right_reads.fastq.gz] -r [genbank_reference.gb] -o [genetic_code] -p [threads] -m [memory]```

or

```singularity run PATH/TO/MitoFinder_v1.4 -j [seqid] -1 [left_reads.fastq.gz] -2 [right_reads.fastq.gz] -r [genbank_reference.gb] -o [genetic_code] -p [threads] -m [memory]```

Please, tell me if it works for you!
Cheers,
Rémi

**Comment by RemiAllio** [comment] 2021-05-04 06:47
Hi!

Has your admin successfully installed singularity version >= 3.0?

Cheers,
Rémi

**Comment by wyj-lzu** [comment] 2021-05-10 13:41
Hi!

Sorry for delay reply. I am busy for other work. Once I install it, I will tell you if it work succefffully

Best.

**Comment by RemiAllio** [comment] 2021-05-10 13:59
Hi!

No worries. However, the link to download it will only be available until May 12. So if you plan to use it, you should download it as soon as possible.

Cheers,
Rémi

**Comment by wyj-lzu** [comment] 2021-05-19 01:07
Hi!

I run the test cases successfully yesterday with the singularity. I will run my own data soon. Thanks a lot for your help 

Best.

**Comment by RemiAllio** [comment] 2021-05-19 10:29
Hi!

Sounds good! 
It was a pleasure to help.

The singularity container in now available to everyone [here](https://github.com/RemiAllio/MitoFinder_container).
Thank you!

Best regards,
Rémi

**Comment by RemiAllio** [comment] 2021-06-16 13:27
Hi,

I hope everything is going well for you now with the singularity container.
Can I close this issue?

Best regards,
Rémi

**Comment by wyj-lzu** [comment] 2021-06-16 13:33
Hi:

OK！ I got it successfully !

谢谢！ ：）

**Comment by RemiAllio** [comment] 2021-06-16 13:38
Great! 
Have a good day :-)
Rémi

**Closed by RemiAllio** 2021-06-16 13:38 UTC
